library(dplyr)
library(ggplot2)
library(plotly)
batting <- read.csv('Batting.csv')
batting <- subset(batting,yearID >= 1985)
salaries <- read.csv('Salaries.csv')
batting$BA <- (batting$H/batting$AB)
batting$X1B <- (batting$H - batting$X2B - batting$X3B - batting$HR)
batting$OBP <- (batting$H + batting$BB + batting$HBP)/(batting$AB + batting$BB + batting$HBP + batting$SF)
batting$SLG <- (batting$X1B + (2*batting$X2B) + (3*batting$X3B) + (4*batting$HR))/(batting$AB)
combo <- merge(batting,salaries,by = c('playerID','yearID'))
lost_players <- subset(combo,playerID %in% c('giambja01','damonjo01','saenzol01'))
lost_players <- subset(lost_players,yearID == 2001)
lost_players <- select(lost_players,c('playerID','H','X2B','X3B','HR','OBP','SLG','BA','AB'))
combo <- subset(combo, yearID==2001)
pl <- ggplot(combo,aes(x=OBP,y=salary)) + geom_point(aes(color=AB))
ggplotly(pl)
combo <- subset(combo,salary < 800000 & OBP < 0.5 & AB > 480)
combo1 <- select(combo,'playerID','OBP','AB','salary')
options <- head(arrange(combo1,desc(OBP),desc(AB),desc(salary)),15)
print(options)
pl2 <- ggplot(options,aes(x=AB,y=salary))+geom_point(aes(color='OBP'))
ggplotly(pl2)